[run]
command = "node build-esbuild.cjs && npx live-server dist-esbuild --host=0.0.0.0 --port=5000 --cors --no-browser"

[deployment]
run = ["node", "build-esbuild.cjs"]
build = ["node", "build-esbuild.cjs"]
deploymentTarget = "gce"

[env]
NODE_ENV = "development"

[[ports]]
localPort = 5000
externalPort = 80

[nix]
channel = "stable-24_05"